[all:vars]
ansible_connection = ansible.netcommon.network_cli
ansible_network_os = cisco.ios.ios
ansible_become = true
ansible_become_password = cisco
ansible_user = cisco
ansible_password = password

[router-1]
192.168.1.24
