- name: "STIG Deployment"
  hosts: router-1
  ignore_errors: true
  tasks: 
    ### Begin benchmarks ###

    - name: CISC-ND-000010
      cisco.ios.ios_config:
        lines:
          - line vty 0 4
          - session-limit 2
          - exit

    - name: CISC-ND-000090
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000100
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000110
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000120
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000150
      cisco.ios.ios_config:
        lines:
          - login block-for 900 attempts 3 within 120

    - name: CISC-ND-000160
      cisco.ios.ios_banner:
        banner: login
        text:  |
          You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.

          By using this IS (which includes any device attached to this IS), you consent to the following conditions:
          
          -The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.

          -At any time, the USG may inspect and seize data stored on this IS.

          -Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.

          -This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.

          -Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.
        state: present

    - name: CISC-ND-000210
      cisco.ios.ios_config:
        lines:
          - logging userinfo          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000280
      cisco.ios.ios_config:
        lines:
          - service timestamps log datetime localtime

    - name: CISC-ND-000380
      cisco.ios.ios_config:
        lines:
          - file privilege 15

    - name: CISC-ND-000390
      cisco.ios.ios_config:
        lines:
          - file privilege 15

    - name: CISC-ND-000460
      cisco.ios.ios_config:
        lines:
          - file privilege 15

    - name: CISC-ND-000620
      cisco.ios.ios_config:
        lines:
          - service password-encryption
    - name: CISC-ND-000720
      cisco.ios.ios_config:
        lines:
          - line vty 0 1
          - exec-timeout 5 0
          - exit
          - line con 0
          - exec-timeout 5 0
          - exit
          - ip http timeout-policy idle 300 life 120 requests 100

    - name: CISC-ND-000880
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-000980
      cisco.ios.ios_config:
        lines:
          - logging buffered 4096 3

    - name: CISC-ND-001000
      cisco.ios.ios_config:
        lines:
          - logging trap 2

    - name: CISC-ND-001030
      cisco.ios.ios_config:
        lines:
          - ntp server 1.1.1.1
          - ntp server 2.2.2.2

    - name: CISC-ND-001130
      cisco.ios.ios_config:
        lines:
          - snmp-server group V3GROUP v3 auth read V3READ write V3WRITE
          - snmp-server user V3USER V3GROUP v3 auth sha password
          - snmp-server view V3READ iso included
          - snmp-server view V3WRITE iso included
          - snmp-server host 1.1.1.1 version 3 auth V3USER    - name: CISC-ND-001200
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2
          - ip ssh server algorithm mac hmac-sha2-256

    - name: CISC-ND-001210
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2
          - ip ssh server algorithm mac hmac-sha2-256
          - ip http secure-ciphersuite aes-128-cbc-sha aes-256-cbc-sha

    - name: CISC-ND-001250
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-001260
      cisco.ios.ios_config:
        lines:
          - login on-failure log
          - login on-success log

    - name: CISC-ND-001270
      cisco.ios.ios_config:
        lines:
          - archive
          - log config
          - logging enable
          - logging size 1000
          - notify syslog contenttype plaintext
          - hidekeys
          - end

    - name: CISC-ND-001440
      cisco.ios.ios_config:
        lines:
          - crypto pki trustpoint CA_X
          - enrollment url http://trustpoint1.example.com
          - exit

    - name: CISC-ND-001450
      cisco.ios.ios_config:
        lines:
          - logging host 1.1.1.1
          - logging host 2.2.2.2

    - name: CISC-ND-001470
      cisco.ios.ios_facts:
        msg: "Cisco IOS version: {{ ansible_net_version }}"

